DECLARE 
	@OBJETO VARCHAR(MAX) = 'Procedure_1' -- informe a procedure pai
	,@FIND VARCHAR(MAX) = 'TB_DBA_SCRIPT_COMPRESSAO' -- informe o objeto que deseja encontrar
	,@ID INT = 1

DECLARE @TB_FIND TABLE ([ID] INT IDENTITY(1,1), [SCHEMA_SP] VARCHAR(255),SPNAME VARCHAR(255), [DATABASE_NAME] VARCHAR(255), [SCHEMA_NAME] VARCHAR(255), OBJETOS VARCHAR(255), [TYPE] VARCHAR(10), CONTROLE VARCHAR(10) NULL)

		INSERT INTO @TB_FIND ([SCHEMA_SP], SPNAME,[DATABASE_NAME],[SCHEMA_NAME],OBJETOS,[TYPE])
		SELECT DISTINCT
			OBJECT_SCHEMA_NAME(REFERENCING_ID) AS SCHEMANAME,
			OBJECT_NAME(REFERENCING_ID) AS SPNAME, 
			REFERENCED_DATABASE_NAME,
			REFERENCED_SCHEMA_NAME,
			REFERENCED_ENTITY_NAME,
			REFERENCED.TYPE
		FROM SYS.SQL_EXPRESSION_DEPENDENCIES
		LEFT JOIN SYS.OBJECTS REFERENCER ON REFERENCING_ID = REFERENCER.OBJECT_ID
		LEFT JOIN SYS.OBJECTS REFERENCED ON REFERENCED_ID = REFERENCED.OBJECT_ID
		WHERE 
			OBJECT_NAME(REFERENCING_ID) = @OBJETO

WHILE 1=1
BEGIN
	SELECT @OBJETO = OBJETOS FROM @TB_FIND WHERE @ID = ID

		INSERT INTO @TB_FIND ([SCHEMA_SP], SPNAME,[DATABASE_NAME],[SCHEMA_NAME],OBJETOS,[TYPE])
		SELECT DISTINCT
			OBJECT_SCHEMA_NAME(REFERENCING_ID) AS SCHEMANAME,
			OBJECT_NAME(REFERENCING_ID) AS SPNAME, 
			REFERENCED_DATABASE_NAME,
			REFERENCED_SCHEMA_NAME,
			REFERENCED_ENTITY_NAME,
			REFERENCED.TYPE
		FROM SYS.SQL_EXPRESSION_DEPENDENCIES
		LEFT JOIN SYS.OBJECTS REFERENCER ON REFERENCING_ID = REFERENCER.OBJECT_ID
		LEFT JOIN SYS.OBJECTS REFERENCED ON REFERENCED_ID = REFERENCED.OBJECT_ID
		WHERE 
			OBJECT_NAME(REFERENCING_ID) = @OBJETO
		
		UPDATE @TB_FIND SET CONTROLE = 'OK' WHERE @ID = ID
		
		SET @ID = @ID + 1

		IF EXISTS(SELECT * FROM @TB_FIND WHERE OBJETOS = @FIND) -- caso não seja o objeto desejado, adicionar mais filtros para ignorar os primeiros resultados
		BEGIN
			BREAK
		END
END

SELECT * FROM @TB_FIND WHERE OBJETOS = @FIND
